/**
 * Theme Registry
 * Manages available themes and provides theme loading functionality
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-theme-registry.js
 * To regenerate, run: npm run generate:themes
 */

import type { ThemeConfig } from './types'
import { defaultTheme } from './default'

// Registry of all available themes (auto-generated)
export const themeRegistry: Record<string, () => Promise<{ default: ThemeConfig }>> = {
  christmas: () => import('./christmas'),
  default: () => import('./default'),
}

// Available theme names
export const availableThemes = Object.keys(themeRegistry)

/**
 * Get a theme by name
 */
export async function getTheme(themeName: string): Promise<ThemeConfig> {
  const themeLoader = themeRegistry[themeName]
  if (!themeLoader) {
    console.warn(`Theme "${themeName}" not found, falling back to default`)
    return defaultTheme
  }
  
  try {
    const module = await themeLoader()
    return module.default
  } catch (error) {
    console.error(`Failed to load theme "${themeName}":`, error)
    return defaultTheme
  }
}

/**
 * Get the default theme synchronously (for SSR)
 */
export function getDefaultTheme(): ThemeConfig {
  return defaultTheme
}
